# Generated by Django 3.2.2 on 2021-06-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_todo_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='false_answer1',
            field=models.CharField(default='NaN', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='false_answer2',
            field=models.CharField(default='NaN', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='false_answer3',
            field=models.CharField(default='NaN', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='genre',
            field=models.CharField(max_length=25),
        ),
    ]
